// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// cdescent
Rcpp::List cdescent(const arma::vec& y, const arma::mat& X, const double& lambda, const int& maxinteration);
RcppExport SEXP _dingfeicdpo_cdescent(SEXP ySEXP, SEXP XSEXP, SEXP lambdaSEXP, SEXP maxinterationSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const double& >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< const int& >::type maxinteration(maxinterationSEXP);
    rcpp_result_gen = Rcpp::wrap(cdescent(y, X, lambda, maxinteration));
    return rcpp_result_gen;
END_RCPP
}
// proxoperator
Rcpp::List proxoperator(arma::vec& y, arma::mat& X, double& lambda, const int& maxinteration);
RcppExport SEXP _dingfeicdpo_proxoperator(SEXP ySEXP, SEXP XSEXP, SEXP lambdaSEXP, SEXP maxinterationSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< double& >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< const int& >::type maxinteration(maxinterationSEXP);
    rcpp_result_gen = Rcpp::wrap(proxoperator(y, X, lambda, maxinteration));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_dingfeicdpo_cdescent", (DL_FUNC) &_dingfeicdpo_cdescent, 4},
    {"_dingfeicdpo_proxoperator", (DL_FUNC) &_dingfeicdpo_proxoperator, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_dingfeicdpo(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
