# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Using the method of "coordinate descent" to get the beta of Lasso problem
#' @param y the response data
#' @param X the design matrix
#' @param lambda the coefficient of the panalty
#' @param maxinteration the maximum of interation
#' @return the list of the beta and object function value in each interation
#' @examples 
#' the data must be regularization before using the function in the package
#' require(dingfeicdpo)
#' standvector = function(y){
#'return(y-mean(y))
#'}
#'standmatrix = function(X){
#'  n=dim(X)[1]
#'  p=dim(X)[2]
#'  meanvec=c()
#'  squarevec=c()
#'  for(i in 1:p){
#'    X[,i]=X[,i]-mean(X[,i])
#'  }
#'  for(j in 1:p){
#'    squarevec=append(squarevec,sum(X[,j]*X[,j]))
#'  }
#'  for(k in 1:p){
#'    X[,k]=X[,k]/(sqrt(squarevec[k]/n))
#'  }
#'  return(X)
#'}
#'n = 100
#'p = 500
#'sigma_noise = 0.5
#'beta = rep(0, p)
#'beta[1:6] = c(5,10,3,80,90,10)
#'X = matrix(rnorm(n*p,sd=10), nrow = n, ncol=p)
#'X_stand=standmatrix(X)
#'y = X_stand %*% beta + rnorm(n, sd = sigma_noise)
#'y_stand=standvector(y)
#'lambda = 0.2
#'maxinteration = 500
#'# Compute Coordinate descent 
NULL

#'# Compute Proximal Operator
#'    betaHat2 = proxoperator(y_stand, X_stand, lambda,maxinteration)
cdescent <- function(y, X, lambda, maxinteration) {
    .Call('_dingfeicdpo_cdescent', PACKAGE = 'dingfeicdpo', y, X, lambda, maxinteration)
}

#' Using the method of "Proximal Operator" to get the beta of Lasso problem
#' @param y the response data
#' @param X the design matrix
#' @param lambda the coefficient of the panalty
#' @param maxinteration the maximum of interation
#' @return the list of the beta and object function value in each interation
#' @examples 
#' the data must be regularization before using the function in the package
#' require(dingfeicdpo)
#' standvector = function(y){
#'return(y-mean(y))
#'}
#'standmatrix = function(X){
#'  n=dim(X)[1]
#'  p=dim(X)[2]
#'  meanvec=c()
#'  squarevec=c()
#'  for(i in 1:p){
#'    X[,i]=X[,i]-mean(X[,i])
#'  }
#'  for(j in 1:p){
#'    squarevec=append(squarevec,sum(X[,j]*X[,j]))
#'  }
#'  for(k in 1:p){
#'    X[,k]=X[,k]/(sqrt(squarevec[k]/n))
#'  }
#'  return(X)
#'}
#'n = 100
#'p = 500
#'sigma_noise = 0.5
#'beta = rep(0, p)
#'beta[1:6] = c(5,10,3,80,90,10)
#'X = matrix(rnorm(n*p,sd=10), nrow = n, ncol=p)
#'X_stand=standmatrix(X)
#'y = X_stand %*% beta + rnorm(n, sd = sigma_noise)
#'y_stand=standvector(y)
#'lambda = 0.2
#'maxinteration = 500
#'# Compute Coordinate descent 
NULL

#'# Compute Proximal Operator
#'    betaHat2 = proxoperator(y_stand, X_stand, lambda,maxinteration)
proxoperator <- function(y, X, lambda, maxinteration) {
    .Call('_dingfeicdpo_proxoperator', PACKAGE = 'dingfeicdpo', y, X, lambda, maxinteration)
}

